services:
  - type: web
    name: portfolio-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: DB_ENGINE
        value: "postgresql"
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: CONTACT_RECEIVER_EMAIL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.12"

databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio_db
