# Generated by Django 6.1.1 on 2026-09-15 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('opportunity_type', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('responded', 'Responded'), ('spam', 'Spam')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('honeypot_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'CV Sent'), ('declined', 'Declined'), ('spam', 'Spam')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('honeypot_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cv_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLinkRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('projects', models.JSONField(default=list)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('links_sent', 'Links Sent'), ('declined', 'Declined'), ('spam', 'Spam')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('honeypot_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_link_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('event_type', models.CharField(choices=[('rate_limit_exceeded', 'Rate Limit Exceeded'), ('honeypot_triggered', 'Honeypot Triggered'), ('invalid_request', 'Invalid Request'), ('form_submitted', 'Form Submitted'), ('form_blocked', 'Form Blocked'), ('admin_login', 'Admin Login'), ('admin_action', 'Admin Action'), ('suspicious_request', 'Suspicious Request'), ('validation_error', 'Validation Error'), ('server_error', 'Server Error')], max_length=50)),
                ('endpoint', models.CharField(max_length=500)),
                ('http_method', models.CharField(max_length=10)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('flagged', 'Flagged')], default='allowed', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_tokens',
            },
        ),
    ]
