# Generated by Django 6.1.1 on 2026-09-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='action_taken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='referrer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('security', 'Security'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('portfolio_visit', 'Portfolio Visit'), ('page_view', 'Page View'), ('project_view', 'Project View'), ('cv_request', 'CV Request'), ('contact_request', 'Contact Request'), ('project_link_request', 'Project Link Request'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('validation_error', 'Validation Error'), ('failed_request', 'Failed Request'), ('unauthorized_access', 'Unauthorized Access'), ('forbidden_request', 'Forbidden Request'), ('invalid_endpoint', 'Invalid Endpoint'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('suspicious_request', 'Suspicious Request'), ('blocked_request', 'Blocked Request'), ('honeypot_triggered', 'Honeypot Triggered'), ('file_upload_violation', 'File Upload Violation'), ('server_error', 'Server Error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='result',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('flagged', 'Flagged'), ('failed', 'Failed')], default='allowed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['event_type'], name='security_lo_event_t_25aa39_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['result'], name='security_lo_result_a439c5_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['severity'], name='security_lo_severit_3e72cc_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['ip_address'], name='security_lo_ip_addr_9afb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['created_at'], name='security_lo_created_9079c7_idx'),
        ),
    ]
